---
- hosts: windowsservers

  vars_prompt:
    - name: password
      prompt: Password for safemode?

  tasks:
    - name: Configure AD
      include_role:
        name: jesperberth.active_directory_domain
      vars:
        domain: "testdomain.local"
        safemodepw: "{{ password }}"
